### ISSUE TITLE
We need to update to our current color palette to Karen's color palatte

### ISSUE THREAD

**Issue by gdostal** [TinleyParkPublicLibrary/tplibrary.org-redesign#1]
Red:                #af5447           rgb(175, 84, 71)          Tertiary color (I'm changing this to more accurately represent the printed color on screens)

Green:            #968447           rgb(150, 132, 71)           Link and anchors

Purple:           #6e587e            rgb(110, 88, 126)          UI elements (esp. buttons)

Blue:               #3b5f6e            rgb(59, 95, 110)           Headers Footers & Primary color

Yellow:           #ffb12c              rgb(255, 177, 44)           UI elements ( buttons )

White: #ffffff rgb(255, 255, 255) body background, text on a dark backgrounds #f5f5f5

Grey(s): examples #575757 #484848 #CCCCCC most text, borders, neutral area backgrounds

Black: #000000 rgb(0, 0, 0) DO NOT USE

**Comment by sfschroeder** [comment]
Working on this. Waiting for a few graphics files from Karen so we can update the logo in the header.
![image](https://cloud.githubusercontent.com/assets/20566911/17037168/2affe1da-4f55-11e6-905e-6bc5b19ff88d.png)
![image](https://cloud.githubusercontent.com/assets/20566911/17037196/5062467a-4f55-11e6-985a-1f2e6292a106.png)

Changed red elements to K's blue, green elements to K's purple, Yellow elements to K's red. Text links are K's green.

Let me know what you think!

S

**Comment by gdostal** [comment]
Just my initial reaction would be to keep a red header. Since the current site has a blue header for the kids/teens section and red for every other page. This way we can kind of keep the same visual look, and not confuse people by inverting our color schemes.

**Comment by sfschroeder** [comment]
Color palette & logo incorporated

**Comment by gdostal** [comment]
Just reopening this so its qucker to refer to.
