### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by sfschroeder** [TinleyParkPublicLibrary/tplibrary.org-redesign#24]
Learn online: 
- [x] Academic Research, w/ link to ebsco & Gale underneath

Homework resources: 
- [x] Landing page for all homework type help incc. databases and other library resources
- [x] Link underneath to test prep
- [x] Tech Skills: direct link to lynda

Consumer guides: 
- [x] Auto repair
- [x] Consumer reports
- [x] Business & Legal
- [x] Health

Languages: 
- [x] little pim
- [x] mango

**Comment by gdostal** [comment]
These have now been completed.
