### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by gdostal** [TinleyParkPublicLibrary/tplibrary.org-redesign#3]
We need to: 
- [x] Give the logo some space
- [x] Move the search box up here
- [x] Add links to the catalog and library account
- [x] Move the main menu below the header
- [x] Change the logo to match Karen's new branding (flat, white logo... files coming)
- [x] The line below the main menu should indicate which page the visitor is on (triangle should point toward active page... css fix?)

In general lets make this look a little more like [my databases page](http://dev.tplibrary.org/sites/default/files/databases.html) header

Mobile menu
- [x] logo will disappear on scrolling page shrinking vertical space
- [x] optionally swap for smaller tp logo
- [x] leaving 
  - [x]   quick links to catalog/accoutn
  - [x]   search box
  - [x]   and menu toggle

**Comment by sfschroeder** [comment]
Commenting to check off some items in above list

**Comment by gdostal** [comment]
Header is finished. Responsive and all.
