### ISSUE TITLE
Quick Links

### ISSUE THREAD

**Issue by gdostal** [TinleyParkPublicLibrary/tplibrary.org-redesign#6]
What should we do with quick links e.g. [Barrington](http://www.barringtonarealibrary.org)?

I would suggest that some of this could be well suited to the page footer.

**Comment by sfschroeder** [comment]
Agreed. I'm not a huge fan of having the quick links at the top (and pushing down content). I think if we organize our main menu (and icons) in an intuitive fashion, we can draw out some of the more commonly accessed information at the bottom, in the footer (e.g. EMPLOYMENT).

Hey, emojis!

**Comment by sfschroeder** [comment]
Spoke to Rich and Anthony. Decided quick links would take form of icons in main body of page. Added additional quick links (about the library, community links, etc.) in the footer region.
