### ISSUE TITLE
Feature our Services

### ISSUE THREAD

**Issue by gdostal** [TinleyParkPublicLibrary/tplibrary.org-redesign#7]
We need to feature our library services. Perhaps with large buttons like [Barrington's](http://www.barringtonarealibrary.org) or [Oak Park](http://www.oppl.org). 

I think my design proposal mostly had the gist of our desires for these elements.
- [x] They need to have a hover overlay to indicate their nature a a link/button
- [x] They need to have some kind of graphic to indicate what type of media can be obtained within
- [ ] It would be nice to have direct links on the button as well for highlighting popular services
- [ ] The buttons could open a drawer below containing all the relevant links to services
- [x] Alternatively they could also link to an interior page.

**Comment by sfschroeder** [comment]
Hover effect, relevant fa-icons added, adjusted padding to reduce vertical space. I'm on the fence about whether to open a drawer to display information about links on the internal page-- if we did, we'd probably want it to perform as a hover effect on desktop and a click effect on mobile. Leaving it as animated icons for now.
