### ISSUE TITLE
Upcoming Events

### ISSUE THREAD

**Issue by gdostal** [TinleyParkPublicLibrary/tplibrary.org-redesign#8]
First, do we even need an upcoming events section? Can we get by with just a link to the calendar instead? 

If we do want a next events section, lets keep it pretty spartan. Here are my requirements:
- [x] Event Title
- [x] Event dates & times
- [ ] It should show upcoming events only if they are drop-in, else we will hide events that are full registration
  - [x] If registration is required we want to show only events that have space available
  - [x] If there is space available we want a Sign Up button
- [x] The view should be limited to the next 3-5 events
- [ ] Events that have happened today, or that just began should fall off

**Comment by sfschroeder** [comment]
I've temporarily inserted an RSS feed widget. I'm not happy with it, but I think it will work for our meeting tomorrow.

S

**Comment by gdostal** [comment]
I've designed the new events section. Obviously some of the unchecked things require Drupal.
