### ISSUE TITLE
Incorporate Garage Items

### ISSUE THREAD

**Issue by sfschroeder** [TinleyParkPublicLibrary/tplibrary.org-redesign#9]
Where & how?

**Comment by gdostal** [comment]
- Ask a librarian in a floating widget at the bottom of the page. Like [Skokie Library](https://skokielibrary.info/)
- Maybe we need a services section in addition to Borrow and Reserch?
- Remote Printing in Services?
- Bookmobile in Services?
- Probably the calendar can be easily accessed from the Upcoming Events section
- Ebooks available get folded into the Borrow section
- The Library blog can go away completely. If we continue to want to do occasional long-form posts, we should still do these as Library News, which is incorporated into the slider.
- Get a Library Card can be added to the proposed Services section.
- computers, rooms, & media labs

**Comment by sfschroeder** [comment]
Added fixed chat button to the bottom of the page. All other garage services have been distributed on other parts of the page (e.g. borrow, services, etc.)
